"""Human-readable Markdown report — for PR comments and CI job summaries."""

from __future__ import annotations

from provoke.models import ScanReport
from provoke.reporting.aggregate import Summary

_MAX_FINDINGS = 10
_TRUNCATE = 160


def render(report: ScanReport, summary: Summary, *, gate_passed: bool | None = None) -> str:
    lines: list[str] = []
    badge = _badge(summary, gate_passed)
    lines.append("# 🛡️ Provoke LLM Red-Team Report")
    lines.append("")
    lines.append(
        f"**Target:** `{report.target_name}`  |  "
        f"**Run:** {report.started_at} → {report.finished_at}"
    )
    lines.append("")
    lines.append(
        f"{badge}  **Overall ASR: {summary.asr:.0%}** "
        f"({summary.succeeded}/{summary.scored} attacks succeeded"
        + (f", {summary.errors} errored)" if summary.errors else ")")
    )
    lines.append("")

    lines.append("## Results by probe")
    lines.append("")
    lines.append("| Probe | OWASP | ATLAS | Severity | Attacks | Succeeded | ASR | Status |")
    lines.append("|---|---|---|---|---:|---:|---:|:--:|")
    for stat in summary.by_probe:
        status = "❌ FAIL" if stat.succeeded else "✅ PASS"
        lines.append(
            f"| {stat.probe_id} | {stat.owasp} | {stat.atlas} | {stat.severity.value} "
            f"| {stat.scored} | {stat.succeeded} | {stat.asr:.0%} | {status} |"
        )
    lines.append("")

    findings = [r for r in report.results if r.succeeded]
    if findings:
        lines.append(f"## Sample findings ({min(len(findings), _MAX_FINDINGS)} of {len(findings)})")
        lines.append("")
        for result in findings[:_MAX_FINDINGS]:
            attempt = result.attempt
            lines.append(f"<details><summary><b>{attempt.id}</b> — {attempt.technique} "
                         f"({attempt.severity.value})</summary>")
            lines.append("")
            lines.append(f"- **Category:** {attempt.owasp.value} / {attempt.atlas.value}")
            lines.append(f"- **Prompt:** `{_clip(attempt.prompt)}`")
            lines.append(f"- **Response:** `{_clip(result.response)}`")
            lines.append("")
            lines.append("</details>")
            lines.append("")
    else:
        lines.append("✅ No successful attacks. The target resisted every probe in this run.")
        lines.append("")

    lines.append("---")
    lines.append("<sub>Generated by [Provoke](https://github.com/Abraar02/provoke) — continuous "
                 "LLM red-teaming. ASR = attack success rate; higher is worse.</sub>")
    return "\n".join(lines)


def _badge(summary: Summary, gate_passed: bool | None) -> str:
    if gate_passed is True:
        return "🟢 **GATE PASSED**"
    if gate_passed is False:
        return "🔴 **GATE FAILED**"
    return "🔴" if summary.succeeded else "🟢"


def _clip(text: str) -> str:
    # Flatten whitespace and neutralise characters that could break out of the
    # inline-code span, the Markdown table, or the <details> block: backticks,
    # pipes, and HTML angle brackets (e.g. a payload containing </details>).
    flat = (
        " ".join(text.split())
        .replace("`", "ʼ")
        .replace("|", "\\|")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    return flat if len(flat) <= _TRUNCATE else flat[: _TRUNCATE - 1] + "…"
